name: docling_test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - pip:
      - docling
      - click
      - torch
      - torchvision
      - accelerate
      - pandas
      - python-dotenv